language: cpp

os:
  - linux

env:
  global:
    - MAKEFLAGS="-j 2"

dist: trusty
sudo: false
addons:
  apt:
    packages:
      - clang
      - libclang-dev

compiler:
  - clang

script:
  - mkdir build
  - cd build
  - cmake -DLIBCLANG_DIR=/usr/lib/llvm-3.4/ ..
  - make
